image: gradle:6.8.3-jdk11

services:
  - postgres:latest

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  POSTGRES_DB: postgres
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres


before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - test
  - staging

test:
  stage: test
  script:
    - gradle :check
    - gradle :jacocoTestReport
    - cat build/reports/jacoco/test/html/index.html

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - $GRADLE_USER_HOME/wrapper
    - $GRADLE_USER_HOME/caches


staging:
  stage: deploy
  trigger:
    project: PramukaBot/PramukaBot
    branch: mini-games
#development:
#  image: ruby:2.4
#  stage: deploy
#  before_script:
#    - gem install dpl
#    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
#  script:
#    - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY
#    - export HEROKU_API_KEY=$HEROKU_APIKEY
#    - heroku run --app $HEROKU_APPNAME migrate
#  environment:
#    name: development
#    url: $HEROKU_APP_HOST
#  only:
#    - master
